services:
  jekyll:
    build: .
    # (optional but recommended) avoid writing to the upstream tag:
    image: sflammia/al-folio-local:dev
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
      - bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development
    command: sh -lc "bundle install && bundle exec jekyll serve --host 0.0.0.0 --port 8080 --livereload"

volumes:
  bundle: